# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Utkarsh Deep
tagline:          'Utkarsh Deep'
description:      'My personal blog of tech and life.'
url:              http://utkarshdeep.github.io

author:
  name:           'Utkarsh Deep'
  url:            http://utkarshdeep.github.io

paginate:         2
google_analytics: 'UA-117152855-1'
emailme:          mailto:utkarshd80@gmail.com
gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/utkarshdeep/utkarshdeep.github.io

tags:

github_username:  utkarshdeep
linkedin_username: utkarsh-deep-34960565


